### PR TITLE
RELATED: RAIL-1531 unify granularity naming

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R182](https://confluence.intgdc.com/display/Dev/R182).
This release is **zero downtime** release.
Code drop: 2019-05-18 00:00.

**Comment by yenkins** [comment]
Story [RAIL-1531](http://jira.intgdc.com/browse/RAIL-1531) Loading Date Filter Configuration from Project Metadata
	Status: Hacking
	Priority: Major
	Assignee: Dan Homola

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/16/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/84/ : SUCCESS in 1m 19s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/8/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/85/ : SUCCESS in 55s

**Pull request merged**
