### PR TITLE
RELATED: SD-973 Overwrite date filter in view/edit mode

### PR DESCRIPTION
**Pull request by ptquang86**
PR for [SD-973](https://jira.intgdc.com/browse/SD-973)

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R209](https://confluence.intgdc.com/display/Dev/R209).
This release is **zero downtime** release.
Code drop: 2020-07-16 00:00.

**Comment by yenkins** [comment]
Story [SD-973](http://jira.intgdc.com/browse/SD-973) KD - Overwrite date filter in view/edit mode
	Status: Hacking
	Priority: Major
	Assignee: Quang Pham

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/120/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/205/ : FAILURE in 44s

**Comment by ptquang86** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/121/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/206/ : FAILURE in 19s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/122/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/207/ : SUCCESS in 30s

**Comment by ptquang86** [comment]
not use

**Pull request closed without merging**
