### PR TITLE
RELATED: SD-889 update type guard for widget

### PR DESCRIPTION
**Pull request by lvkhanh**
Release type: **patch**
Related PR: https://github.com/gooddata/gdc-dashboards/pull/2819

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R206](https://confluence.intgdc.com/display/Dev/R206).
This release is **zero downtime** release.
Code drop: 2020-06-04 00:00.

**Comment by yenkins** [comment]
Story [SD-889](http://jira.intgdc.com/browse/SD-889) KD - Implement to post events in response to GDC application updated
	Status: Hacking
	Priority: Major
	Assignee: Khanh Le

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/102/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/188/ : SUCCESS in 2m 45s

**Comment by ptquang86** [comment]
LGTM

**Comment by naibinh** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/35/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-typings-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/36/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-typings-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by lanhq** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/103/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by lvkhanh** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/104/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by lvkhanh** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/105/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/189/ : SUCCESS in 47s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/37/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-typings-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/38/ : FAILURE in 0s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-typings-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/39/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/190/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/3/ : SUCCESS in 14s (non-voting)

**Pull request merged**
