### PR TITLE
RELATED: SD-886 add IPostMessageContextPayload

### PR DESCRIPTION
**Pull request by lanhq**
## PR checklist
- [x] Passed all test on [gdc-analytical-designer](https://github.com/gooddata/gdc-analytical-designer)

## Related Pull Requests
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3029
- gdc-js-utils: https://github.com/gooddata/gdc-js-utils/pull/91

## Related Jira ticket
- https://jira.intgdc.com/browse/SD-886

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R204](https://confluence.intgdc.com/display/Dev/R204).
This release is **zero downtime** release.
Code drop: 2020-05-07 00:00.

**Comment by yenkins** [comment]
Story [SD-886](http://jira.intgdc.com/browse/SD-886) AD - Implement to post events in response to GDC application updated
	Status: Hacking
	Priority: Major
	Assignee: Lan Huynh

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/75/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/156/ : SUCCESS in 2m 01s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/76/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/157/ : SUCCESS in 1m 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/77/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/158/ : SUCCESS in 1m 40s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/28/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/159/ : SUCCESS in 47s

**Pull request merged**
