### PR TITLE
RELATED: ONE-3610 Support for textual filters in AFM typings

### PR DESCRIPTION
**Pull request by lupko**
- Adds new types under ExecuteAFM namespace; these 1-1 correspond to what backend needs
- Updated AFM positive/negative filter in a backward compatible fashion, to support text filters
- Adds new types (type aliases) to be used as inputs to visualization components (bucket iterface)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/34/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/50/ : SUCCESS in 2m 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/35/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/51/ : SUCCESS in 2m 09s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/36/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/52/ : SUCCESS in 45s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/37/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/53/ : SUCCESS in 3m 10s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/38/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/54/ : SUCCESS in 1m 36s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/41/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/57/ : SUCCESS in 53s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/42/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/58/ : FAILURE in 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/43/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/59/ : SUCCESS in 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/44/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/60/ : SUCCESS in 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/45/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/61/ : SUCCESS in 1m 03s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/46/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/62/ : SUCCESS in 1m 45s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/47/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/63/ : SUCCESS in 23s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/48/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/65/ : SUCCESS in 1m 03s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/49/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/66/ : SUCCESS in 35s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/50/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/67/ : SUCCESS in 1m 07s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/51/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/68/ : SUCCESS in 49s

**Comment by yenkins** [comment]
Currently destined for [release R179](https://confluence.intgdc.com/display/Dev/R179).
This release is **zero downtime** release.
Code drop: 2019-03-23 00:00.

**Comment by yenkins** [comment]
Story [ONE-3610](http://jira.intgdc.com/browse/ONE-3610) Update GoodData.UI SDK to be able to use text filters in AFM instead of element ids
	Status: Hacking
	Priority: Major
	Assignee: Lubomir Slivka

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-evaluated-risk
Ticket should have regression risk evaluated before merging, see [GoodConfluence](https://confluence.intgdc.com/display/office/Labels+In+JIRA#LabelsInJIRA-QA&DELI)
- ONE-3610

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/1/ : UNSTABLE in 32s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by lupko** [comment]
ok to test

**Comment by yenkins** [comment]
Currently destined for [release R180](https://confluence.intgdc.com/display/Dev/R180).
This release is **zero downtime** release.
Code drop: 2019-04-06 00:00.

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: src/AFM.ts
- file added: src/ExecuteAFM.ts
- file added: src/VisualizationInput.ts
- file modified: src/VisualizationObject.ts
- file modified: src/tests/AFM.test.ts
- file added: src/tests/ExecuteAFM.test.ts
- file modified: src/tests/VisualizationObject.test.ts

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/2/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/69/ : SUCCESS in 1m 52s

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file added: src/ExecuteAFM.ts
- file added: src/VisualizationInput.ts
- file added: src/tests/ExecuteAFM.test.ts

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/3/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/70/ : SUCCESS in 52s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/4/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/71/ : SUCCESS in 55s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/1/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/72/ : SUCCESS in 1m 10s

**Pull request merged**
