### PR TITLE
RELATED: ONE-4906 Height of fluid column

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**
Add height definition into IFluidLayoutSize structure

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R224](https://confluence.intgdc.com/display/Dev/R224).
This release is **zero downtime** release.
Code drop: 2021-03-11 00:00.

**Comment by yenkins** [comment]
Story [ONE-4906](http://jira.intgdc.com/browse/ONE-4906) MD Support - Mock JS
	Status: Hacking
	Priority: Major
	Assignee: Ivan Nejezchleb

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: src/DashboardLayout.ts

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#238](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/238/))
Covered lines: **48.95%**, change: **0%**
Covered branches: **68.85%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/239/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/148/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/3/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/239/ : SUCCESS in 1m 13s

**Review by patrikbraborec — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/149/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/4/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/240/ : SUCCESS in 27s

**Review by patrikbraborec — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-typings-gate-PR84

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/50/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/241/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-el7/3/ : SUCCESS in 43s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/13/ : SUCCESS in 12s (non-voting)

**Pull request merged**
