### PR TITLE
TRIVIAL: Rename package.json script to unify it with other repos

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/23/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/31/ : SUCCESS in 42s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/24/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/32/ : SUCCESS in 48s

**Comment by xMort** [comment]
The name of the commit and pull request has been changed according to the Commit policy :)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-merge-compliance-check/9/ : SUCCESS in 2m 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/33/ : SUCCESS in 2m 40s

**Pull request merged**
