### PR TITLE
RELATED: FET-564 Update sonar

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R221](https://confluence.intgdc.com/display/Dev/R221).
This release is **zero downtime** release.
Code drop: 2021-01-14 00:00.

**Comment by yenkins** [comment]
Story [FET-564](http://jira.intgdc.com/browse/FET-564) Fix sonar-reported issues in legacy FE repositories
	Status: Hacking
	Priority: Major
	Assignee: Petr Benes

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file added: .sonar.settings

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#236](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/236/))
Covered lines: **48.95%**, change: **0%**
Covered branches: **68.85%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/237/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/147/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/1/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/237/ : SUCCESS in 50s

**Comment by pbenes** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-typings-check-extended-sonar-PR83

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/2/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-el7/1/ : SUCCESS in 41s (non-voting)

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-typings-gate-PR83

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/49/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/238/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-el7/2/ : SUCCESS in 41s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/12/ : SUCCESS in 2m 01s (non-voting)

**Pull request merged**
