### PR TITLE
RELATED: FET-159 Introduce carets in dependencies

### PR DESCRIPTION
**Pull request by martinmosko**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R185](https://confluence.intgdc.com/display/Dev/R185).
This release is **zero downtime** release.
Code drop: 2019-06-28 00:00.

**Comment by yenkins** [comment]
Story [FET-159](http://jira.intgdc.com/browse/FET-159) Change dependencies to ^
	Status: Hacking
	Priority: Major
	Assignee: Martin Mosko

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-active-sprint
- FET-159
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: yarn.lock

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/20/ : UNSTABLE in 12s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/21/ : UNSTABLE in 10s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by martinmosko** [comment]
ok to test

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: yarn.lock

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/22/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/91/ : SUCCESS in 56s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/11/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/92/ : SUCCESS in 1m 48s

**Pull request merged**
