### PR TITLE
RELATED: FET-793 Upgrade to node16

### PR DESCRIPTION
**Pull request by scavnickyj**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R247](https://confluence.intgdc.com/display/Dev/R247).
This release is **zero downtime** release.
Code drop: 2022-02-24 00:00.

**Comment by yenkins** [comment]
Story [FET-793](http://jira.intgdc.com/browse/FET-793) Upgrade gd infrastructure to node 16
	Status: Hacking
	Priority: Major
	Assignee: Petr Benes

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: .nvmrc

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/157/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/12/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/250/ : SUCCESS in 1m 10s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/158/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/13/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/251/ : SUCCESS in 42s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR89

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/55/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/252/ : SUCCESS in 2m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/5/ : SUCCESS in 33s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/18/ : SUCCESS in 2m 07s (non-voting)

**Pull request merged**
