### PR TITLE
RELATED: BB-2494 Support ranking filter to use it mock-js

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R214](https://confluence.intgdc.com/display/Dev/R214).
This release is **zero downtime** release.
Code drop: 2020-09-24 00:00.

**Comment by yenkins** [comment]
Story [BB-2494](http://jira.intgdc.com/browse/BB-2494) Filter SDK8 visualizations by a ranking filter
	Status: Hacking
	Priority: Major
	Assignee: Petr Dolejsi

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: src/VisualizationInput.ts
- file modified: src/tests/AFM.test.ts
- file modified: src/tests/ExecuteAFM.test.ts
- file modified: src/tests/VisualizationInputs.test.ts

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/144/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/233/ : FAILURE in 36s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/145/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/234/ : FAILURE in 48s

**Comment by yenkins** [comment]
## The code coverage **improved** with your change! 🎉
You are the best! Like literary the best!
#### Report (compared to build [#232](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/232/))
Covered lines: **48.95%**, change: **1.26%**
Covered branches: **68.85%**, change: **1.05%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/235/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/146/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/235/ : SUCCESS in 36s

**Review by yanlipnican — APPROVED** [review]

**Comment by yanlipnican** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/48/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/236/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/11/ : SUCCESS in 11s (non-voting)

**Pull request merged**
