### PR TITLE
RELATED: TNT-1374 Upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by scavnickyj**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R270](https://confluence.intgdc.com/display/Dev/R270).
This release is **zero downtime** release.
Code drop: 2023-03-09 00:00.

**Comment by yenkins** [comment]
Story [TNT-1374](http://gooddata.atlassian.net/browse/TNT-1374) Upgrade packages in TNT-owned repositories (Mar 2023)
	Status: Hacking
	Priority: Major
	Assignee: Jakub Scavnicky

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/162/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker/1/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/17/ : SUCCESS in 4s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR92

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/57/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker/2/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul/1/ : SUCCESS in 2m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/7/ : SUCCESS in 31s

**Pull request merged**
