### PR TITLE
RELATED: RAIL-909 Add type guard functions for Execution

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by tomasreichmann** [comment]
LGTM

**Comment by michalvanco** [comment]
ok to test

**Comment by michalvanco** [comment]
ok to test

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/1/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/1/ : FAILURE in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/7/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/9/ : SUCCESS in 25s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-merge-compliance-check/3/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/10/ : SUCCESS in 23s

**Pull request merged**
