### PR TITLE
RELATED: BB-1127 Add isObjIdentifierQualifier type guard

### PR DESCRIPTION
**Pull request by petrjanu**
Add missing typeguard `isObjIdentifierQualifier`.

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-merge-compliance-check/12/ : ABORTED in 1m 21s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by petrjanu** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-opensource-repository-check/29/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/40/ : SUCCESS in 1m 10s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-merge-compliance-check/13/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/41/ : SUCCESS in 34s

**Pull request merged**
