### PR TITLE
RELATED: SD-970 fix type-guard

### PR DESCRIPTION
**Pull request by lanhq**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R208](https://confluence.intgdc.com/display/Dev/R208).
This release is **zero downtime** release.
Code drop: 2020-07-02 00:00.

**Comment by yenkins** [comment]
Story [SD-970](http://jira.intgdc.com/browse/SD-970) Control filters - Low level message handler
	Status: Hacking
	Priority: Major
	Assignee: Lan Huynh

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/114/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/197/ : SUCCESS in 50s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by ptquang86** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/41/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/200/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/5/ : SUCCESS in 15s (non-voting)

**Pull request merged**
