### PR TITLE
RELATED: RAIL-1531 add project-level EDF config types

### PR DESCRIPTION
**Pull request by no23reason**
Done with https://github.com/gooddata/gdc-bear/commit/9994a737facaf9285c1576634106c310a612792e#diff-e77a0bdeba053db8825bc0c2514a2190 as reference

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R182](https://confluence.intgdc.com/display/Dev/R182).
This release is **zero downtime** release.
Code drop: 2019-05-18 00:00.

**Comment by yenkins** [comment]
Story [RAIL-1531](http://jira.intgdc.com/browse/RAIL-1531) Loading Date Filter Configuration from Project Metadata
	Status: Hacking
	Priority: Major
	Assignee: Dan Homola

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/15/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/82/ : SUCCESS in 1m 11s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/7/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/83/ : SUCCESS in 1m 16s

**Pull request merged**
