### PR TITLE
FEATURE: SD-980 update remove filter context typing

### PR DESCRIPTION
**Pull request by lvkhanh**
release: **patch**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R210](https://confluence.intgdc.com/display/Dev/R210).
This release is **zero downtime** release.
Code drop: 2020-07-30 00:00.

**Comment by yenkins** [comment]
Story [SD-980](http://jira.intgdc.com/browse/SD-980) AD - Allow removing filters
	Status: Hacking
	Priority: Major
	Assignee: Khanh Le

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/131/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/217/ : FAILURE in 1m 05s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/132/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/218/ : SUCCESS in 1m 16s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/134/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/221/ : SUCCESS in 1m 16s

**Comment by ptquang86** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/140/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/226/ : SUCCESS in 1m 09s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-gate check failed
### require-approval
- pull request must be approved

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/45/ : UNSTABLE in 4s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED
- gooddata-typings-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/46/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/230/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/9/ : SUCCESS in 10s (non-voting)

**Pull request merged**
