### PR TITLE
RELATED: FET-249 Use docker image with node 12 LTS

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R201](https://confluence.intgdc.com/display/Dev/R201).
This release is **zero downtime** release.
Code drop: 2020-03-26 00:00.

**Comment by yenkins** [comment]
Story [FET-249](http://jira.intgdc.com/browse/FET-249) Upgrade gd infrastructure to node 12
	Status: New
	Priority: Major
	Assignee: FET Guild User

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file added: .nvmrc
- file modified: docker/.config

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/58/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/138/ : FAILURE in 1m 05s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/59/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/139/ : FAILURE in 48s

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file added: .nvmrc
- file modified: docker/.config
- file modified: src/ExecuteAFM.ts

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/60/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/140/ : SUCCESS in 28s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/25/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/141/ : SUCCESS in 1m 51s

**Pull request merged**
