### PR TITLE
RELATED: SD-559 optional fields to reduce payload

### PR DESCRIPTION
**Pull request by naibinh**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R189](https://confluence.intgdc.com/display/Dev/R189).
This release is **zero downtime** release.
Code drop: 2019-08-23 00:00.

**Comment by yenkins** [comment]
Story [SD-559](http://jira.intgdc.com/browse/SD-559) gooddata-js - Enhance to adapt new PDF export endpoint
	Status: Hacking
	Priority: Major
	Assignee: Binh Nguyen

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/39/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/112/ : SUCCESS in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/40/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/113/ : SUCCESS in 57s

**Comment by lanhq** [comment]
LGTM

**Comment by martinmosko** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/17/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/114/ : SUCCESS in 1m 05s

**Pull request merged**
