### PR TITLE
INFRA-176: Add sonar-project.properties - cfg file for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R266](https://confluence.intgdc.com/display/Dev/R266).
This release is **zero downtime** release.
Code drop: 2022-12-01 00:00.

**Comment by yenkins** [comment]
Epic [INFRA-176](http://gooddata.atlassian.net/browse/INFRA-176) Replace sonarqube with sonarcloud.io
	Status: In Progress
	Priority: Major
	Assignee: Tomas Kouba

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/160/ : UNSTABLE in 7s
- gooddata-typings-unit-tests-zuul-docker : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/15/ : SUCCESS in 6s

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-active-sprint
- INFRA-176
### enforce-ticket-type
Denied ticket types: Epic
- INFRA-176 - Epic

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/161/ : UNSTABLE in 5s
- gooddata-typings-unit-tests-zuul-docker : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/16/ : SUCCESS in 9s

**Pull request closed without merging**
