### PR TITLE
TNT-1621 Node 18 c9s

### PR DESCRIPTION
**Pull request by oleg-morozov**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R280](https://gooddata.atlassian.net/wiki/display/Dev/R280).
This release is **zero downtime** release.
Code drop: 2023-07-27 00:00.

**Comment by yenkins** [comment]
Story [TNT-1621](http://gooddata.atlassian.net/browse/TNT-1621) Frontend apps built with c9s images
	Status: Hacking
	Priority: Major
	Assignee: Oleg Morozov

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/163/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker/3/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/18/ : SUCCESS in 5s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR93

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Pull request merged**
