### PR TITLE
BUGFIX: FET-942 Update jest to fix sonar vulnerabilities

### PR DESCRIPTION
**Pull request by fiedlr**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R245](https://confluence.intgdc.com/display/Dev/R245).
This release is **zero downtime** release.
Code drop: 2022-01-13 00:00.

**Comment by yenkins** [comment]
Epic [FET-809](http://jira.intgdc.com/browse/FET-809) Continuous upgrade of npm packages in frontend applications
	Status: ToDo
	Priority: Major
	Assignee: FET Guild User

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-active-sprint
- FET-809
### enforce-ticket-type
Denied ticket types: Epic
- FET-809 - Epic

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/152/ : UNSTABLE in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/7/ : SUCCESS in 15s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by yenkins** [comment]
Story [FET-942](http://jira.intgdc.com/browse/FET-942) Upgrade some trivial packages to fix sonar vulnerabilities
	Status: Hacking
	Priority: Major
	Assignee: Adam Fiedler

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#245](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/245/))
Covered lines: **48.94%**, change: **-0.01%**
Covered branches: **69.23%**, change: **1.12%** (additional 3 branches are covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/246/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/153/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/8/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/246/ : SUCCESS in 1m 09s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR87

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/53/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/247/ : SUCCESS in 2m 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/3/ : SUCCESS in 31s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/16/ : FAILURE in 1m 51s (non-voting)

**Pull request merged**
