### PR TITLE
RELATED: SD-907 fix naming

### PR DESCRIPTION
**Pull request by lanhq**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R205](https://confluence.intgdc.com/display/Dev/R205).
This release is **zero downtime** release.
Code drop: 2020-05-21 00:00.

**Comment by yenkins** [comment]
Story [SD-907](http://jira.intgdc.com/browse/SD-907) Place sensitive actions under feature flag
	Status: Hacking
	Priority: Major
	Assignee: Lan Huynh

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/96/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/180/ : SUCCESS in 1m 04s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/97/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/181/ : SUCCESS in 49s

**Comment by ptquang86** [comment]
LGTM

**Comment by naibinh** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/33/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/182/ : SUCCESS in 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/1/ : SUCCESS in 13s (non-voting)

**Pull request merged**
