### PR TITLE
RELATED: SD-559 match from/to to backend spec

### PR DESCRIPTION
**Pull request by naibinh**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R189](https://confluence.intgdc.com/display/Dev/R189).
This release is **zero downtime** release.
Code drop: 2019-08-23 00:00.

**Comment by yenkins** [comment]
Story [SD-559](http://jira.intgdc.com/browse/SD-559) gooddata-js - Enhance to adapt new PDF export endpoint
	Status: Hacking
	Priority: Major
	Assignee: Binh Nguyen

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/38/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/110/ : SUCCESS in 2m 07s

**Comment by ptquang86** [comment]
LGTM

**Comment by imnutz** [comment]
LGTM

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-gate check failed
### require-approval
- pull request must be approved

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/15/ : UNSTABLE in 15s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/16/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/111/ : SUCCESS in 52s

**Pull request merged**
