### PR TITLE
TRIVIAL: SPACE-2103 Add license notice and update copyright header

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R245](https://confluence.intgdc.com/display/Dev/R245).
This release is **zero downtime** release.
Code drop: 2022-01-13 00:00.

**Comment by yenkins** [comment]
Sub-task [SPACE-2103](http://jira.intgdc.com/browse/SPACE-2103) OSS Attribution File for gooddata-typings
	Status: Done
	Priority: Major
	Assignee: Petr Dolejsi

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### prohibit-subtask-ticket
Do not reference subtask in commit message summary. It introduces risk of undetected partial changes.
- SPACE-2103
### require-active-sprint
- SPACE-2103
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: LICENSE
- file added: NOTICE.txt

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/154/ : UNSTABLE in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/9/ : SUCCESS in 15s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by xMort** [comment]
ok to test

**Comment by yenkins** [comment]
Sub-task [SPACE-2103](http://jira.intgdc.com/browse/SPACE-2103) OSS Attribution File for gooddata-typings
	Status: In Progress
	Priority: Major
	Assignee: Petr Dolejsi

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### prohibit-subtask-ticket
Do not reference subtask in commit message summary. It introduces risk of undetected partial changes.
- SPACE-2103
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: LICENSE
- file added: NOTICE.txt

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/155/ : UNSTABLE in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/10/ : SUCCESS in 10s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by xMort** [comment]
ok to test

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: LICENSE
- file added: NOTICE.txt

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#247](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/247/))
Covered lines: **48.94%**, change: **0%**
Covered branches: **69.23%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/248/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/156/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/11/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/248/ : SUCCESS in 1m 01s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR88

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/54/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/249/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/4/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/17/ : SUCCESS in 1m 17s (non-voting)

**Pull request merged**
