### PR TITLE
FEATURE: TNT-865 Upgrade packages

### PR DESCRIPTION
**Pull request by oleg-morozov**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R256](https://confluence.intgdc.com/display/Dev/R256).
This release is **zero downtime** release.
Code drop: 2022-07-14 00:00.

**Comment by yenkins** [comment]
Story [TNT-865](http://gooddata.atlassian.net/browse/TNT-865) Upgrade packages in TNT-owned repositories (June 2022)
	Status: Hacking
	Priority: Major
	Assignee: Oleg Morozov

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/159/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/14/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/253/ : SUCCESS in 51s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR90

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/56/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/254/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/6/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/19/ : SUCCESS in 1m 47s (non-voting)

**Pull request merged**
