### PR TITLE
RELATED: FET-803 Upgrade dependencies

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R235](https://confluence.intgdc.com/display/Dev/R235).
This release is **zero downtime** release.
Code drop: 2021-08-12 00:00.

**Comment by yenkins** [comment]
Story [FET-803](http://jira.intgdc.com/browse/FET-803) Upgrade packages in selected UI libs
	Status: Hacking
	Priority: Major
	Assignee: Petr Benes

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#241](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/241/))
Covered lines: **48.95%**, change: **0%**
Covered branches: **68.11%**, change: **-0.74%** (additional 2 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/242/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/150/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/5/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/242/ : SUCCESS in 1m 16s

**Review by patrikbraborec — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR85

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/51/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/243/ : SUCCESS in 1m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/1/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/14/ : FAILURE in 2m 31s (non-voting)

**Pull request merged**
