### PR TITLE
RELATED: BB-1708 Save and load insights with measure value filters

### PR DESCRIPTION
**Pull request by qduval**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R196](https://confluence.intgdc.com/display/Dev/R196).
This release is **zero downtime** release.
Code drop: 2019-12-12 00:00.

**Comment by yenkins** [comment]
Story [BB-1708](http://jira.intgdc.com/browse/BB-1708) Save and load insights with measure value filters
	Status: Hacking
	Priority: Major
	Assignee: Quentin Duval

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/45/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/121/ : SUCCESS in 57s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/20/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/122/ : SUCCESS in 1m 32s

**Pull request merged**
