### PR TITLE
RELATED: ONE-4105 New postEvent for drilling

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R204](https://confluence.intgdc.com/display/Dev/R204).
This release is **zero downtime** release.
Code drop: 2020-05-07 00:00.

**Comment by yenkins** [comment]
Story [ONE-4105](http://jira.intgdc.com/browse/ONE-4105) Remove usage of drill CustomEvent
	Status: Hacking
	Priority: Major
	Assignee: Ivan Nejezchleb

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/78/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/160/ : FAILURE in 59s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/79/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/161/ : SUCCESS in 29s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/29/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/162/ : SUCCESS in 1m 13s

**Pull request merged**
