### PR TITLE
RELATED: FET-157 Upgrade TypeScript

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R181](https://confluence.intgdc.com/display/Dev/R181).
This release is **zero downtime** release.
Code drop: 2019-05-04 00:00.

**Comment by yenkins** [comment]
Story [FET-157](http://jira.intgdc.com/browse/FET-157) Update TypeScript in all components incl. SDK
	Status: Hacking
	Priority: Major
	Assignee: Ivan Nejezchleb

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: yarn.lock

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/10/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/77/ : SUCCESS in 1m 30s

**Comment by yanlipnican** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/4/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/78/ : SUCCESS in 4m 35s

**Pull request merged**
