### PR TITLE
RELATED: FET-550 Use latest image

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R241](https://confluence.intgdc.com/display/Dev/R241).
This release is **zero downtime** release.
Code drop: 2021-11-04 00:00.

**Comment by yenkins** [comment]
Story [FET-550](http://jira.intgdc.com/browse/FET-550) Switch to gdc- prefixed docker image
	Status: Hacking
	Priority: Major
	Assignee: Petr Benes

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#243](https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/243/))
Covered lines: **48.95%**, change: **0%**
Covered branches: **68.11%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/244/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/151/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-oss-check/6/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/244/ : SUCCESS in 1m 21s

**Review by scavnickyj — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-typings-gate-PR86

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/52/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/245/ : SUCCESS in 55s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-sonarqube-scan-zuul-gate/2/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-typings-fossa-scanning-zuul-el7/15/ : SUCCESS in 1m 23s (non-voting)

**Pull request merged**
