### PR TITLE
RELATED: BB-1869 Add isDateFilter type-guard for VisualizationObjectFilters

### PR DESCRIPTION
**Pull request by martinmosko**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R198](https://confluence.intgdc.com/display/Dev/R198).
This release is **zero downtime** release.
Code drop: 2020-02-13 00:00.

**Comment by yenkins** [comment]
Story [BB-1869](http://jira.intgdc.com/browse/BB-1869) Cleanup leftovers after main filter bar refactor
	Status: Hacking
	Priority: Major
	Assignee: Martin Mosko

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/47/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/124/ : SUCCESS in 55s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/21/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/126/ : SUCCESS in 3m 12s

**Pull request merged**
