### PR TITLE
RELATED: BB-2141 mvf treat null as interfaces

### PR DESCRIPTION
**Pull request by strouhaljan**

### CODE REVIEW

**Comment by yenkins** [comment]
Currently destined for [release R201](https://confluence.intgdc.com/display/Dev/R201).
This release is **zero downtime** release.
Code drop: 2020-03-26 00:00.

**Comment by yenkins** [comment]
Story [BB-2141](http://jira.intgdc.com/browse/BB-2141) Allow to treat null values as 0 in MVF
	Status: Hacking
	Priority: Major
	Assignee: Rostislav Listvan

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-active-sprint
- BB-2141
### require-copyright
Invalid or missing copyright, refer [GoodData Copyright Instructions](https://confluence.intgdc.com/display/pap/GoodData+Copyright+Instructions)
- file modified: src/AFM.ts
- file modified: src/ExecuteAFM.ts

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/61/ : UNSTABLE in 7s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by yenkins** [comment]
## client-libs/gooddata-typings-pull-request-compliance-check check failed
### require-active-sprint
- BB-2141

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/62/ : UNSTABLE in 7s
- gooddata-typings-unit-tests-zuul-docker-el7 : SKIPPED

**Comment by strouhaljan** [comment]
ok to test

**Comment by yenkins** [comment]
Currently destined for [release R202](https://confluence.intgdc.com/display/Dev/R202).
This release is **zero downtime** release.
Code drop: 2020-04-09 00:00.

**Comment by yenkins** [comment]
Story [BB-2141](http://jira.intgdc.com/browse/BB-2141) Allow to treat null values as 0 in MVF
	Status: Hacking
	Priority: Major
	Assignee: Petr Dolejsi

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-check/63/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/142/ : SUCCESS in 1m 03s

**Comment by yanlipnican** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-pull-request-compliance-gate/26/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-typings-unit-tests-zuul-docker-el7/143/ : SUCCESS in 51s

**Pull request merged**
